version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
  pre_build:
    commands:
      - echo "Inizio build del frontend React..."
      - cd negozio/frontend
      - npm install
      - npm run build
      - echo "Frontend compilato con successo."
  build:
    commands:
      - echo "Inizio build di Spring Boot con Maven..."
      - cd negozio
      - mvn clean package -DskipTests
      - echo "Backend compilato con successo."
  post_build:
    commands:
      - echo "Preparo i file per Elastic Beanstalk..."
      # Torniamo alla root (se eravamo ancora in negozio) o assicuriamoci di esserci
      - cd $CODEBUILD_SRC_DIR
      - mv negozio/target/*.jar application.jar

artifacts:
  files:
    - application.jar
    - Dockerfile
