spring.application.name=negozio

spring.datasource.url=jdbc:postgresql://localhost:5432/negozio
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
#==================================
# = Messages configuration
#==================================
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8
#==================================
# = Logging configuration
#==================================
logging.level.root=INFO
logging.level.it.uniroma3.siw.negozio.controller.CDController==DEBUG